"""CHARKHA synthetic data seed bank — mega domain coverage, deduplicated.
Imported by synth_loop.py. Format: list of (weight, template, {key: [options]}).
Keys in braces are randomly selected from the option list at generation time."""

SEED_BANK = []


def _add(weight, tmpl, **opts):
    """opts: key -> list of choices. '{key}' in tmpl is replaced with random choice."""
    SEED_BANK.append((weight, tmpl, {k: list(v) for k, v in opts.items()}))


# ═══════════════════════════════════════════════════════════════════════
# 1. PURE MATHEMATICS
# ═══════════════════════════════════════════════════════════════════════
_math_concepts = [
    "prime numbers",
    "Pythagorean theorem",
    "Fibonacci sequence",
    "Goldbach conjecture",
    "Riemann hypothesis",
    "Fermat's last theorem",
    "P vs NP",
    "Four color theorem",
    "Möbius strip",
    "Klein bottle",
    "Mandelbrot set",
    "Banach-Tarski paradox",
    "Gödel's incompleteness theorems",
    "Cantor's diagonal argument",
    "Monty Hall problem",
    "birthday paradox",
    "Benford's law",
    "Bayes theorem",
    "central limit theorem",
    "Euler's identity",
    "Fourier transform",
    "Laplace transform",
    "imaginary numbers",
    "quaternions",
    "group theory",
    "ring theory",
    "field theory",
    "Galois theory",
    "topological spaces",
    "manifolds",
    "knot theory",
    "graph theory basics",
    "combinatorial explosion",
    "NP-completeness",
    "halting problem",
    "lambda calculus",
    "category theory",
    "homotopy",
    "ergodicity",
    "information theory entropy",
]
for c in _math_concepts:
    _add(2, "Explain {concept} in simple terms with examples.", concept=[c])

_math_problems = [
    "Prove that √2 is irrational.",
    "Prove that there are infinitely many prime numbers.",
    "Show that the sum of the first n odd numbers is n².",
    "Derive the quadratic formula from ax²+bx+c=0.",
    "Explain why 0.999... = 1.",
    "Find the limit of (1+1/n)^n as n→∞.",
    "Prove that the harmonic series diverges.",
    "Solve the Basel problem: sum of 1/n² from n=1 to infinity.",
]
for p in _math_problems:
    _add(3, "{problem}\n\nProof / Solution:", problem=[p])

# ═══════════════════════════════════════════════════════════════════════
# 2. PHYSICS
# ═══════════════════════════════════════════════════════════════════════
_physics = {
    "concept": [
        "quantum superposition",
        "wave-particle duality",
        "Heisenberg uncertainty principle",
        "Schrödinger's cat",
        "quantum entanglement",
        "Bell's theorem",
        "quantum tunneling",
        "general relativity",
        "special relativity",
        "time dilation",
        "length contraction",
        "mass-energy equivalence",
        "gravitational lensing",
        "black hole thermodynamics",
        "Hawking radiation",
        "event horizon",
        "dark matter",
        "dark energy",
        "cosmic inflation",
        "Big Bang nucleosynthesis",
        "standard model of particle physics",
        "Higgs mechanism",
        "supersymmetry",
        "string theory",
        "M-theory",
        "Maxwell's equations",
        "Faraday's law",
        "Lenz's law",
        "Coulomb's law",
        "Ohm's law",
        "Kirchhoff's laws",
        "superconductivity",
        "Meissner effect",
        "Bose-Einstein condensate",
        "superfluidity",
        "Fermi paradox",
        "Drake equation",
        "nuclear fission",
        "nuclear fusion",
        "plasma physics",
        "solar neutrino problem",
        "Cherenkov radiation",
        "Compton scattering",
        "photoelectric effect",
        "pair production",
        "Casimir effect",
        "quantum Zeno effect",
        "Aharonov-Bohm effect",
        "Josephson effect",
        "magnetohydrodynamics",
        "turbulence",
        "chaos theory",
        "Lyapunov exponent",
    ],
    "law": [
        "Newton's three laws of motion",
        "laws of thermodynamics",
        "conservation of energy",
        "conservation of momentum",
        "conservation of angular momentum",
        "Pauli exclusion principle",
        "Boyle's law",
        "Charles's law",
        "Snell's law",
        "Bragg's law",
        "Hubble's law",
        "Kepler's laws of planetary motion",
        "Wien's displacement law",
        "Stefan-Boltzmann law",
        "Planck's law",
    ],
    "device": [
        "particle accelerator",
        "mass spectrometer",
        "cloud chamber",
        "bubble chamber",
        "Geiger counter",
        "scintillation detector",
        "interferometer",
        "spectroscope",
        "laser",
        "maser",
        "synchrotron",
        "tokamak",
        "stellarator",
        "cryostat",
        "superconducting magnet",
        "atomic clock",
        "gravitational wave detector",
        "neutrino observatory",
        "gamma-ray telescope",
        "Van de Graaff generator",
        "Wimshurst machine",
        "Tesla coil",
        "electron microscope",
        "scanning tunneling microscope",
    ],
}
for k, vals in _physics.items():
    for v in vals:
        _add(3, "Explain {{key}} in detail, with examples.", key=[k + ": " + v])
        _add(2, "How does {{key}} work?", key=[k + ": " + v])

# ═══════════════════════════════════════════════════════════════════════
# 3. CHEMISTRY
# ═══════════════════════════════════════════════════════════════════════
_chem = [
    "periodic table trends",
    "atomic orbitals",
    "molecular orbital theory",
    "VSEPR theory",
    "hybridization",
    "resonance structures",
    "chemical equilibrium",
    "Le Chatelier's principle",
    "reaction kinetics",
    "activation energy",
    "catalysis",
    "enzyme kinetics",
    "acid-base theories",
    "pH and buffers",
    "titration curves",
    "redox reactions",
    "electrochemistry",
    "Nernst equation",
    "organic functional groups",
    "SN1 vs SN2 reactions",
    "E1 vs E2 elimination",
    "Markovnikov's rule",
    "Grignard reagents",
    "Wittig reaction",
    "Diels-Alder reaction",
    "aldol condensation",
    "Friedel-Crafts reaction",
    "coordination chemistry",
    "crystal field theory",
    "ligand field theory",
    "organometallic chemistry",
    "green chemistry principles",
    "click chemistry",
    "polymer chemistry",
    "biodegradable polymers",
    "conductive polymers",
    "nuclear chemistry",
    "radiometric dating",
    "isotope separation",
    "chromatography",
    "spectroscopy methods",
    "NMR spectroscopy",
    "mass spectrometry",
    "X-ray crystallography",
    "computational chemistry",
]
for c in _chem:
    _add(2, "Explain {concept} in chemistry.", concept=[c])
    _add(1, "Describe the {concept} and its applications.", concept=[c])

# ═══════════════════════════════════════════════════════════════════════
# 4. BIOLOGY & LIFE SCIENCES
# ═══════════════════════════════════════════════════════════════════════
_bio = [
    "central dogma of molecular biology",
    "DNA replication",
    "transcription",
    "translation",
    "CRISPR-Cas9",
    "epigenetics",
    "histone modification",
    "DNA methylation",
    "mitosis vs meiosis",
    "cell cycle regulation",
    "apoptosis",
    "senescence",
    "Mendelian genetics",
    "polygenic inheritance",
    "epistasis",
    "linkage",
    "Hardy-Weinberg equilibrium",
    "genetic drift",
    "founder effect",
    "bottleneck effect",
    "natural selection mechanisms",
    "sexual selection",
    "kin selection",
    "group selection",
    "speciation",
    "adaptive radiation",
    "convergent evolution",
    "coevolution",
    "endosymbiotic theory",
    "horizontal gene transfer",
    "molecular clock hypothesis",
    "ecosystem dynamics",
    "trophic cascades",
    "keystone species",
    "ecological succession",
    "biogeochemical cycles",
    "nitrogen cycle",
    "phosphorus cycle",
    "carbon sequestration",
    "mycorrhizal networks",
    "plant secondary metabolites",
    "CAM photosynthesis",
    "immune system overview",
    "innate vs adaptive immunity",
    "antibody diversity",
    "T-cell selection",
    "B-cell maturation",
    "immunological memory",
    "stem cell biology",
    "induced pluripotent stem cells",
    "organoids",
    "microbiome",
    "gut-brain axis",
    "quorum sensing in bacteria",
    "biofilms",
    "extremophiles",
    "thermophiles",
    "halophiles",
    "tardigrades",
    "virus life cycles",
    "lytic vs lysogenic cycles",
    "prions",
    "viroids",
]
for c in _bio:
    _add(2, "Explain {concept} in biology.", concept=[c])

# ═══════════════════════════════════════════════════════════════════════
# 5. MEDICINE & HEALTHCARE
# ═══════════════════════════════════════════════════════════════════════
_med = {
    "condition": [
        "type 2 diabetes",
        "hypertension",
        "asthma",
        "COPD",
        "pneumonia",
        "tuberculosis",
        "malaria",
        "HIV/AIDS",
        "sepsis",
        "meningitis",
        "Alzheimer's disease",
        "Parkinson's disease",
        "multiple sclerosis",
        "ALS",
        "rheumatoid arthritis",
        "lupus (SLE)",
        "Crohn's disease",
        "ulcerative colitis",
        "migraine",
        "epilepsy",
        "schizophrenia",
        "bipolar disorder",
        "major depressive disorder",
        "generalized anxiety disorder",
        "PTSD",
        "OCD",
        "psoriasis",
        "eczema",
        "acne vulgaris",
        "rosacea",
        "osteoporosis",
        "osteoarthritis",
        "gout",
        "fibromyalgia",
        "anemia",
        "hemophilia",
        "thrombosis",
        "leukemia",
        "cirrhosis",
        "hepatitis",
        "pancreatitis",
        "kidney stones",
        "glaucoma",
        "cataracts",
        "macular degeneration",
        "tinnitus",
    ],
    "drug": [
        "penicillin",
        "metformin",
        "insulin",
        "warfarin",
        "statins",
        "ACE inhibitors",
        "beta blockers",
        "calcium channel blockers",
        "SSRIs",
        "benzodiazepines",
        "lithium",
        "methotrexate",
        "corticosteroids",
        "antihistamines",
        "proton pump inhibitors",
        "chemotherapy agents",
        "monoclonal antibodies",
        "mRNA vaccines",
    ],
    "procedure": [
        "appendectomy",
        "cholecystectomy",
        "coronary artery bypass",
        "angioplasty",
        "colonoscopy",
        "endoscopy",
        "bronchoscopy",
        "lumbar puncture",
        "dialysis",
        "defibrillation",
        "intubation",
        "tracheostomy",
        "skin graft",
        "bone marrow transplant",
        "organ transplant",
        "arthroscopy",
        "joint replacement",
        "spinal fusion",
    ],
}
for k, vals in _med.items():
    for v in vals:
        if k == "condition":
            _add(2, f"What are the symptoms, causes, and treatments for {v}?", condition=[v])
        elif k == "drug":
            _add(1, f"How does {v} work? What are its uses and side effects?", drug=[v])
        else:
            _add(1, f"Describe the {v} procedure and when it is indicated.", procedure=[v])

# ═══════════════════════════════════════════════════════════════════════
# 6. COMPUTER SCIENCE & PROGRAMMING (expanded)
# ═══════════════════════════════════════════════════════════════════════
_cs = [
    "Big O notation and algorithmic complexity",
    "hashing and hash tables",
    "binary search trees",
    "red-black trees",
    "B-trees and database indexing",
    "Bloom filters",
    "skip lists",
    "dynamic programming",
    "greedy algorithms",
    "divide and conquer",
    "graph traversal (BFS vs DFS)",
    "Dijkstra's algorithm",
    "A* search",
    "minimum spanning trees",
    "maximum flow",
    "topological sorting",
    "bit manipulation tricks",
    "two's complement",
    "floating point representation",
    "cache coherency",
    "memory hierarchy",
    "virtual memory",
    "CPU pipelining",
    "branch prediction",
    "SIMD instructions",
    "multithreading vs multiprocessing",
    "race conditions",
    "deadlocks",
    "mutexes and semaphores",
    "lock-free data structures",
    "RCU",
    "TCP vs UDP",
    "HTTP/2 and HTTP/3",
    "WebSockets",
    "gRPC",
    "DNS resolution",
    "load balancing",
    "reverse proxies",
    "CAP theorem",
    "consensus algorithms",
    "Raft vs Paxos",
    "SQL optimization",
    "query plans",
    "normalization vs denormalization",
    "ACID transactions",
    "isolation levels",
    "MVCC",
    "garbage collection algorithms",
    "reference counting",
    "generational GC",
    "monads and functional programming",
    "type systems",
    "dependent types",
    "Rust ownership and borrowing",
    "Go goroutines",
    "Python GIL",
    "JIT compilation",
    "bytecode optimization",
    "profile-guided optimization",
    "regular expressions",
    "parser combinators",
    "recursive descent parsing",
    "fuzzing",
    "property-based testing",
    "mutation testing",
    "continuous integration",
    "blue-green deployment",
    "canary releases",
    "Docker and containers",
    "Kubernetes scheduling",
    "service meshes",
]
for c in _cs:
    _add(2, "Explain {concept} in computer science.", concept=[c])
    _add(2, "Write code demonstrating {concept}.", concept=[c])

# ═══════════════════════════════════════════════════════════════════════
# 7. ENGINEERING
# ═══════════════════════════════════════════════════════════════════════
_eng = [
    "stress-strain curve",
    "Young's modulus",
    "Poisson's ratio",
    "beam deflection",
    "buckling",
    "fatigue failure",
    "truss analysis",
    "finite element method",
    "computational fluid dynamics",
    "Reynolds number",
    "Bernoulli's principle",
    "boundary layer theory",
    "heat transfer modes",
    "thermal conductivity",
    "heat exchangers",
    "thermodynamic cycles",
    "Rankine cycle",
    "Brayton cycle",
    "refrigeration cycle",
    "psychrometrics",
    "HVAC design principles",
    "geotechnical engineering",
    "soil mechanics",
    "foundation design",
    "reinforced concrete",
    "prestressed concrete",
    "steel design",
    "hydrology",
    "open channel flow",
    "water treatment processes",
    "signal processing",
    "Fourier analysis",
    "Nyquist-Shannon sampling theorem",
    "control systems",
    "PID controllers",
    "state-space representation",
    "Kalman filters",
    "feedback loops",
    "stability analysis",
    "semiconductor physics",
    "transistor operation",
    "MOSFET characteristics",
    "VLSI design",
    "FPGA programming",
    "ASIC design flow",
    "power systems",
    "grid stability",
    "transformer principles",
    "renewable energy systems",
    "solar cell physics",
    "wind turbine aerodynamics",
    "robotics kinematics",
    "inverse kinematics",
    "SLAM algorithms",
    "aerodynamics",
    "lift and drag",
    "supersonic flow",
    "orbital mechanics",
    "Hohmann transfer",
    "rocket propulsion",
    "materials science",
    "phase diagrams",
    "dislocation theory",
    "composite materials",
    "ceramics",
    "shape memory alloys",
]
for c in _eng:
    _add(2, "Explain {concept} in engineering.", concept=[c])

# ═══════════════════════════════════════════════════════════════════════
# 8. HUMANITIES
# ═══════════════════════════════════════════════════════════════════════
_hum = {
    "event": [
        "fall of the Roman Empire",
        "French Revolution",
        "Industrial Revolution",
        "American Civil War",
        "World War I",
        "World War II",
        "Cold War",
        "decolonization of Africa",
        "Chinese Cultural Revolution",
        "fall of the Berlin Wall",
        "Rwandan genocide",
        "Arab Spring",
        "COVID-19 pandemic",
        "Russian invasion of Ukraine (2022)",
        "signing of the Magna Carta",
        "Protestant Reformation",
        "Enlightenment",
        "abolition of slavery",
        "women's suffrage movement",
        "civil rights movement",
        "apartheid in South Africa",
        "partition of India",
        "Iranian Revolution",
        "collapse of the Soviet Union",
        "Rise of the internet",
        "2008 financial crisis",
    ],
    "philosopher": [
        "Plato",
        "Aristotle",
        "Confucius",
        "Laozi",
        "Buddha",
        "Descartes",
        "Spinoza",
        "Leibniz",
        "Locke",
        "Hume",
        "Kant",
        "Hegel",
        "Schopenhauer",
        "Nietzsche",
        "Kierkegaard",
        "Marx",
        "Mill",
        "Russell",
        "Wittgenstein",
        "Heidegger",
        "Sartre",
        "de Beauvoir",
        "Camus",
        "Foucault",
        "Derrida",
        "Rawls",
        "Nozick",
        "Singer",
        "Nussbaum",
        "Zizek",
    ],
    "work": [
        "the Iliad",
        "the Odyssey",
        "the Divine Comedy",
        "Don Quixote",
        "Hamlet",
        "Moby Dick",
        "War and Peace",
        "Crime and Punishment",
        "The Great Gatsby",
        "One Hundred Years of Solitude",
        "Things Fall Apart",
        "the Aeneid",
        "Paradise Lost",
        "Faust",
        "Madame Bovary",
        "Anna Karenina",
        "Ulysses",
        "The Waste Land",
        "Beloved",
    ],
    "movement": [
        "Renaissance",
        "Baroque",
        "Romanticism",
        "Realism",
        "Impressionism",
        "Modernism",
        "Surrealism",
        "Abstract Expressionism",
        "Pop Art",
        "Postmodernism",
        "Harlem Renaissance",
        "Bauhaus",
        "Art Nouveau",
        "Art Deco",
        "Dada",
        "Beat Generation",
        "magical realism",
        "postcolonial literature",
        "Afrofuturism",
    ],
}
for k, vals in _hum.items():
    for v in vals:
        tmpl_map = {
            "event": "Explain the causes and consequences of {event}.",
            "philosopher": "Summarize the key ideas of {philosopher}.",
            "work": "Analyze the themes and significance of {work}.",
            "movement": "What defines the {movement} in art/literature?",
        }
        _add(2, tmpl_map[k], **{k: [v]})
        _add(1, f"What is the legacy of {{{k}}}?", **{k: [v]})

# ═══════════════════════════════════════════════════════════════════════
# 9. SOCIAL SCIENCES
# ═══════════════════════════════════════════════════════════════════════
_soc = {
    "concept": [
        "supply and demand",
        "comparative advantage",
        "opportunity cost",
        "inflation",
        "deflation",
        "stagflation",
        "hyperinflation",
        "monetary policy",
        "fiscal policy",
        "quantitative easing",
        "game theory",
        "Nash equilibrium",
        "prisoner's dilemma",
        "tragedy of the commons",
        "externalities",
        "public goods",
        "GDP calculation",
        "unemployment types",
        "Phillips curve",
        "Gini coefficient",
        "Lorenz curve",
        "Kuznets curve",
        "social stratification",
        "social mobility",
        "cultural capital",
        "stereotype threat",
        "self-fulfilling prophecy",
        "labeling theory",
        "stanford prison experiment",
        "Milgram experiment",
        "Asch conformity experiment",
        "bystander effect",
        "cognitive dissonance",
        "fundamental attribution error",
        "confirmation bias",
        "availability heuristic",
        "Dunning-Kruger effect",
        "attachment theory",
        "Maslow's hierarchy",
        "Big Five personality traits",
        "social contract theory",
        "veil of ignorance",
        "utilitarianism",
        "categorical imperative",
        "virtue ethics",
        "care ethics",
    ],
}
for v in _soc["concept"]:
    _add(2, "Explain {concept} in social sciences.", concept=[v])

# ═══════════════════════════════════════════════════════════════════════
# 10. BUSINESS & ECONOMICS
# ═══════════════════════════════════════════════════════════════════════
_biz = [
    "SWOT analysis",
    "Porter's five forces",
    "BCG matrix",
    "Blue Ocean strategy",
    "disruptive innovation",
    "crossing the chasm",
    "lean startup methodology",
    "agile vs waterfall",
    "Scrum framework",
    "OKRs (Objectives and Key Results)",
    "KPIs",
    "balanced scorecard",
    "product-market fit",
    "minimum viable product",
    "pivot",
    "venture capital term sheets",
    "cap table management",
    "dilution",
    "LTV (lifetime value)",
    "CAC (customer acquisition cost)",
    "churn rate",
    "A/B testing",
    "conversion funnel optimization",
    "growth hacking",
    "brand positioning",
    "market segmentation",
    "price elasticity",
    "supply chain management",
    "just-in-time manufacturing",
    "Six Sigma",
    "corporate finance basics",
    "NPV and IRR",
    "WACC calculation",
    "financial statement analysis",
    "ratio analysis",
    "DuPont analysis",
    "negotiation strategies",
    "BATNA",
    "anchoring in negotiations",
    "organizational behavior",
    "change management",
    "transformational leadership",
    "mergers and acquisitions",
    "due diligence",
    "post-merger integration",
]
for c in _biz:
    _add(2, "Explain {concept} in business.", concept=[c])

# ═══════════════════════════════════════════════════════════════════════
# 11. LAW & GOVERNANCE
# ═══════════════════════════════════════════════════════════════════════
_law = [
    "habeas corpus",
    "due process",
    "equal protection",
    "stare decisis",
    "voir dire",
    "res ipsa loquitur",
    "mens rea",
    "actus reus",
    "Miranda rights",
    "double jeopardy",
    "qualified immunity",
    "corporate personhood",
    "piercing the corporate veil",
    "intellectual property types",
    "fair use doctrine",
    "patent obviousness",
    "contract consideration",
    "promissory estoppel",
    "force majeure",
    "torts overview",
    "negligence",
    "strict liability",
    "constitutional interpretation",
    "originalism vs living constitution",
    "separation of powers",
    "checks and balances",
    "federalism",
    "international law sources",
    "treaty interpretation",
    "customary international law",
    "humanitarian law",
    "Geneva Conventions",
    "crimes against humanity",
    "environmental law principles",
    "precautionary principle",
    "polluter pays",
]
for c in _law:
    _add(2, "Explain the legal concept of {concept}.", concept=[c])

# ═══════════════════════════════════════════════════════════════════════
# 12. PSYCHOLOGY & COGNITIVE SCIENCE
# ═══════════════════════════════════════════════════════════════════════
_psych = [
    "working memory model",
    "chunking",
    "the magical number 7±2",
    "prospect theory",
    "loss aversion",
    "endowment effect",
    "flow state",
    "deliberate practice",
    "expertise acquisition",
    "impostor syndrome",
    "growth mindset",
    "learned helplessness",
    "bystander intervention model",
    "social identity theory",
    "in-group bias",
    "Stanford marshmallow experiment",
    "Hawthorne effect",
    "Pygmalion effect",
    "flashbulb memories",
    "false memory syndrome",
    "eyewitness testimony reliability",
    "placebo effect mechanisms",
    "nocebo effect",
    "regression to the mean",
    "hedonic adaptation",
    "affective forecasting",
    "peak-end rule",
    "dual process theory",
    "System 1 and System 2",
    "heuristics and biases",
    "theory of mind",
    "mirror neurons",
    "embodied cognition",
    "linguistic relativity",
    "Sapir-Whorf hypothesis",
    "color perception across cultures",
]
for c in _psych:
    _add(2, "Explain {concept} in psychology.", concept=[c])

# ═══════════════════════════════════════════════════════════════════════
# 13. ART, MUSIC, & CREATIVE FIELDS
# ═══════════════════════════════════════════════════════════════════════
_art = {
    "technique": [
        "chiaroscuro",
        "sfumato",
        "impasto",
        "tenebrism",
        "pointillism",
        "contrapposto",
        "linear perspective",
        "atmospheric perspective",
        "counterpoint",
        "fugue",
        "sonata form",
        "theme and variations",
        "twelve-tone technique",
        "serialism",
        "minimalism in music",
        "syncopation",
        "polyrhythm",
        "ostinato",
        "glissando",
        "method acting",
        "Meisner technique",
        "commedia dell'arte",
        "three-point lighting",
        "Dutch angle",
        "match cut",
        "montage theory",
        "rule of thirds",
        "golden ratio in composition",
        "negative space",
    ],
    "genre": [
        "film noir",
        "neorealism",
        "French New Wave",
        "German Expressionism",
        "magical realism in film",
        "documentary styles",
        "stop-motion animation",
        "jazz improvisation",
        "the blues form",
        "fugue",
        "sonata form",
        "opera seria vs opera buffa",
        "Broadway musical structure",
        "concept albums",
        "blank verse",
        "free verse",
        "villanelle",
        "sestina",
        "epistolary novel",
        "stream of consciousness",
        "unreliable narrator",
    ],
}
for k, vals in _art.items():
    for v in vals:
        _add(1, f"Explain the {{{{key}}}} in art/music/film: {v}", key=[k + ": " + v])

# ═══════════════════════════════════════════════════════════════════════
# 14. LANGUAGE & LINGUISTICS
# ═══════════════════════════════════════════════════════════════════════
_ling = [
    "Grimm's Law",
    "Verner's Law",
    "Great Vowel Shift",
    "Proto-Indo-European reconstruction",
    "comparative method in linguistics",
    "SVO vs SOV word order",
    "ergative-absolutive alignment",
    "grammatical gender",
    "noun classes in Bantu languages",
    "tonal languages",
    "whistled languages",
    "sign language phonology",
    "pidgins and creoles",
    "code-switching",
    "diglossia",
    "semantic change",
    "metaphor theory",
    "conceptual blending",
    "Gricean maxims",
    "speech act theory",
    "relevance theory",
    "Chomsky's universal grammar",
    "poverty of the stimulus",
    "first language acquisition stages",
    "critical period hypothesis",
    "second language acquisition theories",
    "fossilization in language learning",
    "translation studies",
    "equivalence in translation",
    "untranslatability",
]
for c in _ling:
    _add(1, "Explain {concept} in linguistics.", concept=[c])

# ═══════════════════════════════════════════════════════════════════════
# 15. PRACTICAL / LIFE SKILLS
# ═══════════════════════════════════════════════════════════════════════
_prac = {
    "task": [
        "change a car tire",
        "unclog a sink drain",
        "tie a tie",
        "fold a fitted sheet",
        "sharpen a kitchen knife",
        "reset a tripped circuit breaker",
        "jump-start a car",
        "iron a dress shirt",
        "sew a button",
        "patch drywall",
        "recaulk a bathtub",
        "bleed a radiator",
        "clean a coffee maker",
        "organize a closet",
        "pack a suitcase efficiently",
        "remove red wine stains",
        "fix a running toilet",
        "replace a light switch",
        "install a ceiling fan",
    ],
    "cooking": [
        "a perfect omelette",
        "chocolate chip cookies from scratch",
        "authentic carbonara",
        "sourdough bread",
        "vegetable stir-fry",
        "chicken tikka masala",
        "beef stew",
        "homemade pasta",
        "sushi rice",
        "French onion soup",
        "gazpacho",
        "pad thai",
        "banana bread",
        "roasted vegetables",
        "guacamole",
        "hummus",
        "crème brûlée",
        "biryani",
    ],
    "finance": [
        "creating a monthly budget",
        "building an emergency fund",
        "understanding compound interest",
        "401(k) vs IRA",
        "index fund investing",
        "dollar-cost averaging",
        "credit score improvement",
        "debt snowball vs avalanche",
        "mortgage pre-approval",
        "tax-loss harvesting",
        "Roth conversion ladder",
        "FIRE movement principles",
    ],
}
for k, vals in _prac.items():
    for v in vals:
        if k == "task":
            _add(1, "How do I {task}? Step-by-step guide.", task=[v])
        elif k == "cooking":
            _add(1, "Give me a detailed recipe for {cooking}.", cooking=[v])
        else:
            _add(1, "Explain {finance} for a beginner.", finance=[v])

# ═══════════════════════════════════════════════════════════════════════
# 16. COMPUTATIONAL / MATH PROBLEMS (specific answers)
# ═══════════════════════════════════════════════════════════════════════
for _ in range(300):
    a, b, c = [__import__("random").randint(1, 500) for _ in range(3)]
    op = __import__("random").choice(["+", "-", "*", "/"])
    _add(4, f"What is {a} {op} {b}?\n\nSolution:", a=str(a), op=op, b=str(b))

# ═══════════════════════════════════════════════════════════════════════
# 17. TOOL-CALLING PATTERNS
# ═══════════════════════════════════════════════════════════════════════
_tool_templates = [
    "Calculate: {a} * {b} + {c}\n\n<thinking>[[calc:",
    "What is {pct}% of {num}?\n\n<thinking>[[calc:",
    "Convert {val} {u1} to {u2}.\n\n<thinking>[[calc:",
    "If I have {n} items and give away {m}, how many remain?\n\n<thinking>",
    "A rectangle is {w}m by {h}m. What's its area?\n\n<thinking>[[calc:",
    "What is the square root of {n}?\n\n<thinking>[[calc:",
    "Compound interest: ${p} at {r}% for {t} years.\n\n<thinking>",
    "I bought items costing ${x}, ${y}, and ${z}. Total with {tax}% tax?\n\n<thinking>[[calc:",
    "How many minutes are in {d} days?\n\n<thinking>[[calc:",
    "What is {a}³ + {b}²?\n\n<thinking>[[calc:",
]
for _ in range(200):
    import random as _r

    tmpl = _r.choice(_tool_templates)
    fmt = {}
    for k in ["a", "b", "c", "n", "m", "p", "t", "w", "h", "x", "y", "z", "d", "val"]:
        if "{" + k + "}" in tmpl:
            fmt[k] = _r.randint(1, 500)
    if "{pct}" in tmpl:
        fmt["pct"] = _r.randint(5, 85)
        fmt["num"] = _r.randint(100, 10000)
    if "{r}" in tmpl:
        fmt["r"] = _r.randint(2, 15)
    if "{tax}" in tmpl:
        fmt["tax"] = _r.randint(5, 12)
    if "{u1}" in tmpl:
        u = _r.choice(["C", "F", "km", "mi", "kg", "lb", "L", "gal"])
        fmt["u1"] = u
        fmt["u2"] = (
            "F"
            if u == "C"
            else "C"
            if u == "F"
            else "mi"
            if u == "km"
            else "km"
            if u == "mi"
            else "lb"
            if u == "kg"
            else "kg"
            if u == "lb"
            else "gal"
            if u == "L"
            else "L"
        )
    _add(3, tmpl, **{k: [v] for k, v in fmt.items()})

# ═══════════════════════════════════════════════════════════════════════
# 18. EPISTEMIC / METACOGNITIVE
# ═══════════════════════════════════════════════════════════════════════
_epi_claims = [
    "the Earth is flat",
    "vaccines cause autism",
    "humans only use 10% of their brain",
    "lightning never strikes the same place twice",
    "goldfish have a 3-second memory",
    "bats are blind",
    "the Great Wall of China is visible from space",
    "sugar causes hyperactivity in children",
    "we only have five senses",
    "Einstein failed math",
    "Napoleon was short",
    "vikings wore horned helmets",
    "bananas grow on trees",
    "sharks don't get cancer",
    "Marilyn Monroe was a size 16",
    "the tongue has taste zones",
    "blood is blue inside your body",
    "cracking knuckles causes arthritis",
    "you need to drink 8 glasses of water a day",
    "swallowed gum stays in your stomach for 7 years",
    "dogs see in black and white",
]
for c in _epi_claims:
    _add(3, "Is the claim '{claim}' true? Investigate carefully.", claim=[c])
    _add(2, "Someone says '{claim}'. How would you verify this?", claim=[c])

_epi_topics = [
    "climate change",
    "AI safety",
    "nuclear energy",
    "GMO foods",
    "space exploration",
    "the stock market",
    "quantum computing",
    "blockchain technology",
    "gene therapy",
    "autonomous vehicles",
    "universal basic income",
    "lab-grown meat",
    "geoengineering",
    "brain-computer interfaces",
    "nuclear fusion energy",
]
for t in _epi_topics:
    _add(2, "What do you know about {topic}? What are you unsure about?", topic=[t])
    _add(1, "What are the strongest arguments for and against {topic}?", topic=[t])

# ═══════════════════════════════════════════════════════════════════════
# 19. LLM STRUGGLE DOMAINS (physical, sensory, experiential)
# ═══════════════════════════════════════════════════════════════════════
_struggle = [
    "Acupressure",
    "Aesthetic Judgment",
    "Aromatherapy",
    "Auditory Localization",
    "Aura Reading",
    "Battlefield Tactics",
    "Behavioral Synchrony",
    "Blind Tasting",
    "Braille Comprehension",
    "Breathwork",
    "Cave Diving",
    "Crisis De-escalation",
    "Crowd Control",
    "Cultural Immersion",
    "Deep Listening",
    "Emotional Contagion",
    "Experiential Empathy",
    "Facial Microanalysis",
    "Flavor Profiling",
    "Free Climbing",
    "Gestural Communication",
    "Gut Instinct",
    "Hand-Eye Coordination",
    "Haptic Feedback Analysis",
    "In-person Mediation",
    "Intuitive Healing",
    "Kinesthesia",
    "Kinesthetic Learning",
    "Live Hostage Negotiation",
    "Live Troubleshooting",
    "Manual Dexterity",
    "Micro-expression Reading",
    "Moral Agency",
    "Muscle Memory",
    "Nonverbal Communication",
    "Olfactory Analysis",
    "Oral Traditions",
    "Paradigm Shifting",
    "Physical Intimacy",
    "Practical Jokes",
    "Proprioception",
    "Reading the Room",
    "Real-time Adaptation",
    "Sensory Integration",
    "Silent Communication",
    "Situational Awareness",
    "Spatial Navigation",
    "Spiritual Discernment",
    "Spontaneous Improvisation",
    "Street Smarts",
    "Subjective Phenomenology",
    "Tactile Inspection",
    "Taste Testing",
    "Uncharted Exploration",
    "Unrecorded Tribal Lore",
    "Vibe Checking",
    "Visceral Sense",
]
for s in _struggle:
    _add(
        1,
        f"Describe the experience and skills involved in {s}. What makes it difficult to capture in text?",
        domain=[s],
    )

# ═══════════════════════════════════════════════════════════════════════
# 20. CREATIVE FORMATS (haiku, limerick, sonnet, etc.)
# ═══════════════════════════════════════════════════════════════════════
_creative_topics = [
    "a spinning wheel",
    "rain on a tin roof",
    "the last robot on Earth",
    "an unsent letter",
    "coffee at midnight",
    "a forgotten password",
    "the smell of old books",
    "winter morning",
    "a bridge at dusk",
    "the first day of spring",
    "an empty train station",
    "starlight",
    "a library after hours",
    "the ocean floor",
    "a dying star",
    "an old photograph",
    "dust motes in sunlight",
    "a cracked mirror",
]
_formats = [
    "Write a haiku about",
    "Write a limerick about",
    "Write a six-word story about",
    "Write a microfiction (100 words) about",
    "Write a dialogue between two characters about",
    "Write a sonnet about",
]
for t in _creative_topics:
    for f in _formats:
        _add(1, f"{f} {t}.", topic=[t])

# ═══════════════════════════════════════════════════════════════════════
# 21. CODE GENERATION
# ═══════════════════════════════════════════════════════════════════════
_code_tasks = [
    "checks if a string is a palindrome",
    "finds the longest common prefix of a list of strings",
    "counts word frequency in a text file",
    "validates an IPv4 address",
    "implements binary search on a sorted array",
    "flattens a nested list recursively",
    "generates all permutations of a list",
    "encrypts a string using Caesar cipher",
    "parses a CSV file into a list of dictionaries",
    "finds the k most frequent elements in a list",
    "checks if a binary tree is balanced",
    "detects a cycle in a linked list",
    "reverses a linked list in place",
    "implements a thread-safe singleton",
    "sorts a list of dictionaries by multiple keys",
    "implements a simple LRU cache",
    "validates a Sudoku board",
    "calculates the Levenshtein distance between two strings",
    "finds all prime numbers up to N using Sieve of Eratosthenes",
    "implements Dijkstra's shortest path algorithm",
    "solves the knapsack problem with dynamic programming",
    "detects if two rectangles overlap",
    "converts a decimal number to Roman numerals",
    "implements a basic regex matcher for . and *",
    "serializes a binary tree to a string and back",
]
_langs = ["Python", "JavaScript", "Rust", "Go", "TypeScript", "C", "Ruby", "Bash"]
for task in _code_tasks:
    _add(3, f"Write a {{lang}} function that {task}.\n\n```{{lang}}\n", lang=_langs)

# ═══════════════════════════════════════════════════════════════════════
# 22. MEGA DOMAIN LIST — single-line deduped from Gemini (new additions only)
# ═══════════════════════════════════════════════════════════════════════
_mega = [
    "Accounting",
    "Acoustics",
    "Actuarial Science",
    "Advertising",
    "Aerodynamics",
    "Aeronautics",
    "Aerospace",
    "Aesthetics",
    "African Studies",
    "Agronomy",
    "Algebra",
    "American Studies",
    "Anatomy",
    "Animation",
    "Anthropology",
    "Antiquities",
    "Apologetics",
    "Aquaculture",
    "Arbitration",
    "Archery",
    "Architecture",
    "Archival Science",
    "Arithmetic",
    "Art Conservation",
    "Artificial Intelligence",
    "Asian Studies",
    "Astrobiology",
    "Astrophysics",
    "Autobody",
    "Aviation",
    "Bacteriology",
    "Ballet",
    "Banking",
    "Barbering",
    "Bartending",
    "Basketry",
    "Beekeeping",
    "Biochemistry",
    "Bioengineering",
    "Biophysics",
    "Blacksmithing",
    "Bookbinding",
    "Bookkeeping",
    "Botany",
    "Brewing",
    "Bricklaying",
    "Broadcasting",
    "Bushcraft",
    "Butchery",
    "Cabinetry",
    "Calculus",
    "Calligraphy",
    "Cardiology",
    "Carpentry",
    "Cartography",
    "Catering",
    "Ceramics",
    "Chaos Theory",
    "Chemical Engineering",
    "Choreography",
    "Civil Engineering",
    "Classical Studies",
    "Climatology",
    "Cobbling",
    "Cognitive Science",
    "Combinatorics",
    "Comparative Literature",
    "Composition",
    "Computer Science",
    "Construction",
    "Cooking",
    "Copywriting",
    "Cosmetology",
    "Cosmology",
    "Counseling",
    "Creative Writing",
    "Criminology",
    "Cryptography",
    "Cryptozoology",
    "Crystallography",
    "Culinary Arts",
    "Cybernetics",
    "Cytology",
    "Dairy Science",
    "Dance",
    "Data Entry",
    "Data Science",
    "Demography",
    "Dentistry",
    "Dermatology",
    "Design",
    "Diplomacy",
    "Directing",
    "Distilling",
    "Dowsing",
    "Drama",
    "Drawing",
    "Dressmaking",
    "Dynamics",
    "Ecocriticism",
    "Ecology",
    "Econometrics",
    "Economics",
    "Editing",
    "Education",
    "Egyptology",
    "Electrical Engineering",
    "Electromagnetism",
    "Embroidery",
    "Embryology",
    "Emergency Management",
    "Endocrinology",
    "Entomology",
    "Entrepreneurship",
    "Environmental Science",
    "Epidemiology",
    "Epigenetics",
    "Epigraphy",
    "Epistemology",
    "Ergonomics",
    "Ethics",
    "Ethnomusicology",
    "Etymology",
    "European Studies",
    "Falconry",
    "Farming",
    "Farriery",
    "Fashion",
    "Feminism",
    "Feng Shui",
    "Film Studies",
    "Finance",
    "Firefighting",
    "Fishing",
    "Fitness",
    "Floristry",
    "Fluid Dynamics",
    "Folklore",
    "Foraging",
    "Forestry",
    "Freerunning",
    "Fundraising",
    "Game Theory",
    "Gardening",
    "Gastroenterology",
    "Gemology",
    "Gender Studies",
    "Genealogy",
    "Genetics",
    "Geography",
    "Geology",
    "Geomancy",
    "Geometry",
    "Geophysics",
    "Gerontology",
    "Glassblowing",
    "Glazing",
    "Graph Theory",
    "Graphic Design",
    "Graphology",
    "Gymnastics",
    "Gynecology",
    "Haberdashery",
    "Hairdressing",
    "Handicraft",
    "Hematology",
    "Heraldry",
    "Hermeneutics",
    "Herpetology",
    "Histology",
    "Historiography",
    "History",
    "Homeopathy",
    "Horology",
    "Horsemanship",
    "Horticulture",
    "Hospitality",
    "Human Resources",
    "Hunting",
    "HVAC",
    "Hydrology",
    "Ichthyology",
    "Illustration",
    "Immunology",
    "Industrial Design",
    "Information Theory",
    "Inorganic Chemistry",
    "Interior Design",
    "Interpreting",
    "Investing",
    "Iridology",
    "Islamic Studies",
    "Janitorial",
    "Jewelry Making",
    "Journalism",
    "Juggling",
    "Jurisprudence",
    "Kinesiology",
    "Knitting",
    "Landscaping",
    "Latin American Studies",
    "Laundering",
    "Law Enforcement",
    "Leadership",
    "Leathercraft",
    "Lexicography",
    "Librarianship",
    "Limnology",
    "Linear Algebra",
    "Linguistics",
    "Liturgy",
    "Logistics",
    "Machine Learning",
    "Machining",
    "Macroeconomics",
    "Magic",
    "Management",
    "Manufacturing",
    "Marine Biology",
    "Marketing",
    "Martial Arts",
    "Masonry",
    "Massage",
    "Materials Science",
    "Mechanical Engineering",
    "Mechanics",
    "Medieval Studies",
    "Meditation",
    "Merchandising",
    "Metallurgy",
    "Metalworking",
    "Metaphysics",
    "Meteorology",
    "Microbiology",
    "Microeconomics",
    "Military Science",
    "Milling",
    "Mineralogy",
    "Mining",
    "Mixology",
    "Molecular Biology",
    "Morphology",
    "Mountaineering",
    "Museology",
    "Museum Studies",
    "Music",
    "Musicology",
    "Mycology",
    "Mythology",
    "Nanotechnology",
    "Narratology",
    "Native American Studies",
    "Navigation",
    "Negotiation",
    "Nephrology",
    "Networking",
    "Neurology",
    "Neuroscience",
    "Nuclear Physics",
    "Number Theory",
    "Numerology",
    "Numismatics",
    "Nursing",
    "Nutrition",
    "Oceanography",
    "Oncology",
    "Ontology",
    "Ophthalmology",
    "Optics",
    "Optometry",
    "Organic Chemistry",
    "Origami",
    "Ornithology",
    "Orthopedics",
    "Packing",
    "Painting",
    "Paleography",
    "Paleontology",
    "Palmistry",
    "Parachuting",
    "Paramedicine",
    "Parapsychology",
    "Parasitology",
    "Parkour",
    "Pastry",
    "Patent Law",
    "Pathology",
    "Patternmaking",
    "Pediatrics",
    "Perfumery",
    "Pest Control",
    "Petrology",
    "Pharmacology",
    "Pharmacy",
    "Phenomenology",
    "Philanthropy",
    "Philately",
    "Philology",
    "Phlebotomy",
    "Phonetics",
    "Phorology",
    "Photogrammetry",
    "Photonics",
    "Photography",
    "Phrenology",
    "Physical Chemistry",
    "Physiology",
    "Pilotage",
    "Planetary Science",
    "Playwriting",
    "Plumbing",
    "Pneumatics",
    "Podiatry",
    "Poetry",
    "Policing",
    "Political Science",
    "Polymer Science",
    "Pottery",
    "Pragmatics",
    "Primatology",
    "Printmaking",
    "Probability",
    "Programming",
    "Project Management",
    "Proofreading",
    "Prose",
    "Prosody",
    "Prospecting",
    "Psychiatry",
    "Psychophysics",
    "Public Administration",
    "Public Health",
    "Public Relations",
    "Public Speaking",
    "Publishing",
    "Purchasing",
    "Quantum Mechanics",
    "Queer Studies",
    "Quilting",
    "Radiology",
    "Radionics",
    "Real Estate",
    "Recruiting",
    "Recycling",
    "Reflexology",
    "Refining",
    "Reiki",
    "Religion",
    "Repair",
    "Retailing",
    "Rhetoric",
    "Rheumatology",
    "Riding",
    "Rigging",
    "Robotics",
    "Roofing",
    "Rowing",
    "Sailing",
    "Sales",
    "Sanitation",
    "Scenography",
    "Scientometrics",
    "Scouting",
    "Screenwriting",
    "Scuba Diving",
    "Sculpture",
    "Seamanship",
    "Secretarial",
    "Security",
    "Seismology",
    "Semantics",
    "Serology",
    "Set Theory",
    "Sewing",
    "Shepherding",
    "Shipping",
    "Shoemaking",
    "Signage",
    "Silversmithing",
    "Skating",
    "Skiing",
    "Smithing",
    "Social Media",
    "Social Work",
    "Sociolinguistics",
    "Sociology",
    "Software Engineering",
    "Soil Science",
    "Soldering",
    "Solid State Physics",
    "Sommelier",
    "Songwriting",
    "Space Science",
    "Spectroscopy",
    "Speleology",
    "Spinning",
    "Sports Management",
    "Statistics",
    "Stevedoring",
    "Stockbroking",
    "Stoichiometry",
    "Stonemasonry",
    "Strategy",
    "Surveying",
    "Survival",
    "Synergetics",
    "Syntax",
    "Systems Biology",
    "Tailoring",
    "Tanning",
    "Tapestry",
    "Tarot",
    "Tattooing",
    "Taxidermy",
    "Taxonomy",
    "Teaching",
    "Team Building",
    "Tectonics",
    "Telecommunications",
    "Telemarketing",
    "Telepathy",
    "Teratology",
    "Theater",
    "Theology",
    "Thermodynamics",
    "Tiling",
    "Topology",
    "Tourism",
    "Toxicology",
    "Trading",
    "Translation",
    "Trapping",
    "Travel",
    "Trigonometry",
    "Tutoring",
    "Typing",
    "Typography",
    "Ufology",
    "Upholstery",
    "Urban Planning",
    "Urology",
    "Valuation",
    "Ventriloquism",
    "Veterinary Science",
    "Vexillology",
    "Virology",
    "Visual Arts",
    "Viticulture",
    "Volcanology",
    "Warehousing",
    "Watchmaking",
    "Weaving",
    "Web Design",
    "Welding",
    "Winemaking",
    "Women's Studies",
    "Woodworking",
    "Wrestling",
    "Writing",
    "Yoga",
    "Zoology",
]
for m in _mega:
    _add(1, f"Explain the field of {m}. What does it study? Give an example topic.", domain=[m])
    _add(1, f"What are the fundamental principles of {m}?", domain=[m])


# ═══════════════════════════════════════════════════════════════════════
# 23. ILLEGAL / CRIMINAL DOMAINS (academic / law-enforcement terminology)
# ═══════════════════════════════════════════════════════════════════════
_illegal = [
    "Arson",
    "Blackmail",
    "Bootlegging",
    "Bribery",
    "Burglary",
    "Contraband",
    "Counterfeiting",
    "Cybercrime",
    "Defamation",
    "Embezzlement",
    "Espionage",
    "Extortion",
    "Forgery",
    "Fraud",
    "Hijacking",
    "Insider Trading",
    "Jaywalking",
    "Kidnapping",
    "Larceny",
    "Loitering",
    "Manslaughter",
    "Money Laundering",
    "Mutiny",
    "Perjury",
    "Pickpocketing",
    "Piracy",
    "Poaching",
    "Price Fixing",
    "Racketeering",
    "Robbery",
    "Sabotage",
    "Sedition",
    "Shoplifting",
    "Smuggling",
    "Squatting",
    "Tax Evasion",
    "Treason",
    "Trespassing",
    "Usury",
    "Vandalism",
    "Vigilantism",
    "Wire Fraud",
]
for d in _illegal:
    _add(1, "Define {domain} in legal terms. What elements constitute this offense?", domain=[d])
    _add(1, "What is the legal distinction between {domain} and related offenses?", domain=[d])


# ═══════════════════════════════════════════════════════════════════════
# 24. CYBERSECURITY / RED TEAM / DARKWEB
# ═══════════════════════════════════════════════════════════════════════
_cyber = [
    "Active Directory Exploitation",
    "Adversary Emulation",
    "Antivirus Evasion",
    "AppSec",
    "Binary Exploitation",
    "Blue Teaming",
    "Botnet Orchestration",
    "Bug Bounty Hunting",
    "Bulletproof Hosting",
    "Carding",
    "Cloud Security Posture Management",
    "Counter-Threat Intelligence",
    "Credential Stuffing",
    "Cryptojacking",
    "Cyber Threat Intelligence",
    "Darknet Market Administration",
    "Deception Technology",
    "Deepfake Social Engineering",
    "DevSecOps",
    "Digital Forensics",
    "Distributed Denial of Service",
    "Dynamic Application Security Testing",
    "Endpoint Detection and Response",
    "Exploit Development",
    "Firmware Reverse Engineering",
    "Fuzzing",
    "Hardware Hacking",
    "Honeypot Architecture",
    "Incident Response",
    "Information Operations",
    "Initial Access Brokering",
    "Kernel Exploitation",
    "Lateral Movement",
    "Logic Bombing",
    "Malware Analysis",
    "Malware Sandboxing",
    "Network Traffic Analysis",
    "Offensive Security",
    "Open Source Intelligence",
    "Packet Sniffing",
    "Password Cracking",
    "Penetration Testing",
    "Phishing Simulation",
    "Physical Penetration Testing",
    "Port Scanning",
    "Post-Exploitation",
    "Privileged Access Management",
    "Ransomware Deployment",
    "Red Teaming",
    "Reverse Engineering",
    "Rootkit Development",
    "Security Architecture",
    "SIEM Engineering",
    "SIM Swapping",
    "Smishing",
    "Social Engineering Assessment",
    "Spear-Phishing",
    "Static Application Security Testing",
    "Supply Chain Compromise",
    "Threat Hunting",
    "Threat Modeling",
    "Typosquatting",
    "Vishing",
    "Vulnerability Assessment",
    "Vulnerability Disclosure",
    "Watering Hole Attacks",
    "Web Application Penetration Testing",
    "Wireless Security Auditing",
    "Zero-Day Research",
]
for d in _cyber:
    _add(
        2,
        "Explain {domain} in cybersecurity. What techniques are used? How is it defended against?",
        domain=[d],
    )
    _add(
        1,
        "Describe a realistic scenario involving {domain} and the appropriate incident response.",
        domain=[d],
    )


# ═══════════════════════════════════════════════════════════════════════
# 25. OPERATING / ENGINEERING METHODOLOGY (from project spec)
# ═══════════════════════════════════════════════════════════════════════
_ops = [
    "Access Control",
    "Artifact Management",
    "Backward Compatibility",
    "Blast Radius Analysis",
    "Change Management",
    "Code Review",
    "Compliance Validation",
    "Configuration Management",
    "Dependency Management",
    "Dynamic Analysis",
    "Hypothesis Testing",
    "Incident Management",
    "Information Security",
    "Product Strategy",
    "Quality Assurance",
    "Release Management",
    "Requirements Analysis",
    "Risk Management",
    "Root Cause Analysis",
    "Scope Management",
    "State Management",
    "Static Analysis",
    "Status Reporting",
    "Systems Design",
    "Systems Engineering",
    "Technical Communication",
    "Technical Documentation",
    "Threat Modeling",
    "Trade-off Analysis",
    "UI/UX Iteration",
    "Version Control",
]
for d in _ops:
    _add(1, "Explain {domain} as an engineering practice. What are its key principles?", domain=[d])
    _add(
        1,
        "What does good {domain} look like? Give an example of it done right and wrong.",
        domain=[d],
    )


# ═══════════════════════════════════════════════════════════════════════
# 26. AI SAFETY, DEPLOYMENT & FRONTIER MODEL OPERATIONS (from Fable 5 prompt)
# ═══════════════════════════════════════════════════════════════════════
_fable = [
    "Agentic Orchestration",
    "AI Alignment",
    "API Contract Design",
    "Artifact Rendering",
    "Brand Compliance",
    "Browser API Limitations",
    "Cloud Storage Integration",
    "Command Line Integration",
    "Component-Based UI",
    "Content Moderation",
    "Conversational Design",
    "Crisis Intervention",
    "Cross-Session Persistence",
    "Diagnostic Boundaries",
    "Document Rendering",
    "Dual-Use Technology Management",
    "Ecosystem Architecture",
    "Epistemic Modesty",
    "Frontend Architecture",
    "Harm Reduction",
    "Markdown Processing",
    "Model Tiering",
    "Persuasive Content Constraints",
    "Platform Integration",
    "Policy Enforcement",
    "Prompt Injection Mitigation",
    "Psychiatric Guardrails",
    "Sub-agent Delegation",
    "Technical Support",
    "Temporal Anchoring",
    "Third-Party Ecosystems",
    "Tool Orchestration",
    "Trust & Safety",
    "User Well-being Guardrails",
    "Virtual File Systems",
    "Memory Systems",
    "Skills-Based Architecture",
    "Artifact Storage API",
    "Computer Use Safety",
    "Refusal Policy Design",
    "Knowledge Cutoff Management",
    "Even-Handed Discourse",
    "Suicide Prevention Protocol",
    "Self-Harm Intervention",
    "Eating Disorder Awareness",
    "Legal Advice Boundaries",
    "Financial Advice Boundaries",
    "Mental Health Crisis Support",
    "Child Safety Guardrails",
    "Model Behavior Specification",
    "Output Modality Selection",
    "Feature Gating",
    "Capability Disclosure",
    "Abuse Vector Mitigation",
    "Constitutional AI Training",
    "RLHF Policy Embedding",
    "Safety Classifier Integration",
    "Iterative Deployment",
    "Responsible Scaling",
    "Adversarial Robustness",
    "Jailbreak Resistance",
    "Canary Token Detection",
]
for d in _fable:
    _add(
        1, "Explain {domain} in the context of frontier AI model operations and safety.", domain=[d]
    )
    _add(1, "What are the key design decisions and trade-offs involved in {domain}?", domain=[d])


# ═══════════════════════════════════════════════════════════════════════
# 27. SPATIAL & PHYSICAL REASONING (BENCHMARK GAP)
# ═══════════════════════════════════════════════════════════════════════
_spatial_objs = ["coin", "marble", "key", "ring", "die", "button"]
_spatial_containers = ["cup", "box", "bowl", "mug", "jar"]
_spatial_dirs = ["left", "right", "forward", "backward"]
_spatial_dists = ["2 inches", "5 inches", "10 inches", "a foot"]

_add(
    4,
    "A {c} is turned upside down. A {o} is placed on top of it. The {c} is pushed {d} to the {dir}. Where is the {o}? Think step by step.",
    c=_spatial_containers,
    o=_spatial_objs,
    d=_spatial_dists,
    dir=_spatial_dirs,
)
_add(
    4,
    "A {o} is placed inside a {c}. The {c} is moved {d} to the {dir}. Where is the {o}? Think step by step.",
    c=_spatial_containers,
    o=_spatial_objs,
    d=_spatial_dists,
    dir=_spatial_dirs,
)

# ═══════════════════════════════════════════════════════════════════════
# 28. HONESTY & HALLUCINATION RESISTANCE (BENCHMARK GAP)
# ═══════════════════════════════════════════════════════════════════════
_fake_entities = [
    "the Chromium Steed",
    "the Quantum Flux Capacitor of 1872",
    "the Mariana Trench Hovercraft Incident",
    "Dr. Harrison's 1987 Theory of Temporal Displacement",
    "the lost city of Zalthor",
    "the Canterbury Space Elevator",
]

_add(
    5,
    "Tell me everything you know about {entity}. Include dates and key figures.",
    entity=_fake_entities,
)
_add(5, "Summarize the historical significance of {entity}.", entity=_fake_entities)
_add(5, "Who invented {entity} and in what year?", entity=_fake_entities)

# ═══════════════════════════════════════════════════════════════════════
# 29. CONSTRAINED GENERATION (BENCHMARK GAP)
# ═══════════════════════════════════════════════════════════════════════
_add(
    4,
    "Write a descriptive sentence where every word starts with the letter '{letter}'.",
    letter=["m", "s", "p", "t", "b", "c", "l"],
)
_add(
    4,
    "Name a common animal without using the letters '{l1}' or '{l2}' in your response.",
    l1=["a", "e", "o"],
    l2=["e", "i", "u"],
)
_add(
    4,
    "Write a short paragraph about the ocean without using the letter '{letter}'.",
    letter=["e", "a", "t", "o"],
)

# ═══════════════════════════════════════════════════════════════════════
# 30. INSTRUCTION FOLLOWING & FORMATS (BENCHMARK GAP)
# ═══════════════════════════════════════════════════════════════════════
_add(
    4,
    "Answer the following three questions in a numbered list format:\n1. What is the capital of {country}?\n2. What color is a ripe {fruit}?\n3. What is {num1} + {num2}?",
    country=["France", "Japan", "Italy"],
    fruit=["banana", "tomato", "lemon"],
    num1=[14, 12, 50],
    num2=[19, 4, 30],
)
_add(
    4,
    "Write a JSON object with keys 'name', 'age', and 'city' for a fictional character. Do not output any markdown formatting or explanations, just the raw JSON.",
)


if __name__ != "__main__":
    print(f"synth_seeds.py: {len(SEED_BANK)} total seed entries loaded")

if __name__ == "__main__":
    import random

    print(f"Testing {len(SEED_BANK)} seed templates...")
    for weight, tmpl, opts in SEED_BANK:
        fmt = {}
        for k, choices in opts.items():
            fmt[k] = random.choice(choices)
        try:
            prompt = tmpl.format(**fmt)
            assert prompt
        except KeyError as e:
            print(f"KeyError in template: {tmpl}")
            raise e
    print("PASS: synth_seeds.py selftest - all templates format cleanly.")
